testbench for "dsPIC33FJ64GS606" is
begin
   process is
   begin
      OSCCON.COSC <= "011";
      OSCCON.LOCK <= '1';
      ACLKCON.APLLCK <= '1';
      wait for 1 ic;
   end process;

   -- Keep RD11 asserted.
   process is
   begin
      RD0 <= '1';
      RD11 <= '1';
      RD6 <= '0';
      wait;
   end process;

   process is
   begin
      ADCBUF1  <= 688;
      ADCBUF3  <= 917;
      ADCBUF4  <= 10;
      ADCBUF6  <= 158;
      ADCBUF7  <= 974;
      ADCBUF8  <= 1023;
      ADCBUF9  <= 0;
      ADCBUF10 <= 692;
      ADCBUF11 <= 607;
      ADCBUF12 <= 0;
      ADCBUF13 <= 233;
      ADCBUF14 <= 0;
      ADCBUF15 <= 1019;
      wait;
   end process;

   process is
   begin
      ADCBUF0 <= 520;
      ADCBUF2 <= 522;
      ADCBUF5 <= 525;
      wait for 150000 ic;

      ADCBUF0 <= 580;
      ADCBUF2 <= 582;
      ADCBUF5 <= 585;
      wait for 150000 ic;

      ADCBUF0 <= 620;
      ADCBUF2 <= 622;
      ADCBUF5 <= 625;
      wait for 150000 ic;

      ADCBUF0 <= 650;
      ADCBUF2 <= 652;
      ADCBUF5 <= 655;
      wait for 150000 ic;

      ADCBUF0 <= 680;
      ADCBUF2 <= 682;
      ADCBUF5 <= 685;
      wait;
   end process;
end testbench;
